name: Refresh pages

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    refresh:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Reset gh-pages to latest main
              run: |
                  git fetch origin
                  git checkout gh-pages
                  git reset --hard origin/main
                  git push origin gh-pages --force
